### PR TITLE
Add Unicode 1/7, 1/9, and 1/10

### PR DESCRIPTION
**Pull request by benkasminbullock**
The module omits three of the Unicode fractions. See here:

https://www.lemoda.net/tools/unicode/index.html?char=2152

### CODE REVIEW

**Review by vanHoesel — CHANGES_REQUESTED** [review]
please add these fractions also after line 322, adding them to the list of regular expressions.

**Review by vanHoesel — CHANGES_REQUESTED** [review]
Please add tests to 19_unicode_simple, to ensure the module recognises the new introduced fractions

**Comment by benkasminbullock** [comment]
To be clear, should I be doing this or should Dave Cross be?

**Comment by davorg** [comment]
@benkasminbullock It'll be far more likely to be released quickly if you do it :-)

**Comment by benkasminbullock** [comment]
See the other pull request.

**Pull request closed without merging**
